/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.visao;

import br.com.controle.Questao2JornadaC;
import javax.swing.JOptionPane;

/**
 *
 * @author Admin
 */
public class Questao2JornadaV extends javax.swing.JFrame {

    Questao2JornadaC c = new Questao2JornadaC();

    /**
     * Creates new form Questao2JornadaV
     */
    public Questao2JornadaV() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTmatrícula = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jB40hrs = new javax.swing.JButton();
        jB44hrs = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLvotos40 = new javax.swing.JLabel();
        jLvotos44 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLfuncTot = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLmaiorVoto = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Digite sua matrícula:");

        jTmatrícula.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTmatrículaActionPerformed(evt);
            }
        });
        jTmatrícula.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTmatrículaKeyReleased(evt);
            }
        });

        jLabel2.setText("Escolha uma das opções de horas:");

        jB40hrs.setText("40hrs");
        jB40hrs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB40hrsActionPerformed(evt);
            }
        });

        jB44hrs.setText("44hrs");
        jB44hrs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB44hrsActionPerformed(evt);
            }
        });

        jLabel3.setText("Votos 40 hrs:");

        jLabel4.setText("Votos 44 hrs:");

        jLvotos40.setForeground(new java.awt.Color(255, 0, 0));
        jLvotos40.setText("0");

        jLvotos44.setForeground(new java.awt.Color(255, 0, 0));
        jLvotos44.setText("0");

        jLabel5.setText("Ao total ");

        jLfuncTot.setForeground(new java.awt.Color(0, 0, 255));
        jLfuncTot.setText("0");

        jLabel7.setText("funcionários votaram.");

        jLabel10.setText("Resultado da votação:");

        jLmaiorVoto.setForeground(new java.awt.Color(0, 0, 255));
        jLmaiorVoto.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTmatrícula, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jB40hrs)
                                .addComponent(jLabel3))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel4)
                                .addComponent(jB44hrs))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addGap(18, 18, 18)
                        .addComponent(jLmaiorVoto))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLvotos40)
                            .addComponent(jLabel5))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLfuncTot)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel7))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(95, 95, 95)
                                .addComponent(jLvotos44)))))
                .addContainerGap(154, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTmatrícula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jB40hrs)
                    .addComponent(jB44hrs))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLvotos40)
                    .addComponent(jLvotos44))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLfuncTot)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLmaiorVoto))
                .addContainerGap(79, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jB40hrsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB40hrsActionPerformed
        // TODO add your handling code here:
        jLvotos40.setText("" + c.voto40OF());
        ajusteGeral();
    }//GEN-LAST:event_jB40hrsActionPerformed

    private void ajusteGeral() {
        if (!c.matriculaPreenchida()) {
            JOptionPane.showMessageDialog(null, "Preencha a matrícula!");          
        }
            jTmatrícula.setText("");
            jTmatrícula.requestFocus();
            jLfuncTot.setText("" + c.votosTotais());
            jLmaiorVoto.setText(c.maiorVoto());
            c.setMatricula("");
    }

    private void jB44hrsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB44hrsActionPerformed
        // TODO add your handling code here:
        jLvotos44.setText("" + c.voto44OF());
        ajusteGeral();
    }//GEN-LAST:event_jB44hrsActionPerformed

    private void jTmatrículaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTmatrículaKeyReleased
        // TODO add your handling code here:
        c.setMatricula(jTmatrícula.getText());
    }//GEN-LAST:event_jTmatrículaKeyReleased

    private void jTmatrículaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTmatrículaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTmatrículaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Questao2JornadaV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Questao2JornadaV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Questao2JornadaV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Questao2JornadaV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Questao2JornadaV().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jB40hrs;
    private javax.swing.JButton jB44hrs;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLfuncTot;
    private javax.swing.JLabel jLmaiorVoto;
    private javax.swing.JLabel jLvotos40;
    private javax.swing.JLabel jLvotos44;
    private javax.swing.JTextField jTmatrícula;
    // End of variables declaration//GEN-END:variables
}
